name: Tests

on:
    push:
        branches: main
    pull_request:

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v4
          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
            with:
                # To install LaTeX to build PDF book 
                tinytex: true 
                # version: 1.3
          - name: Setup Julia
            uses: julia-actions/setup-julia@latest
            with:
                version: 1.9
          - name: Julia Cache
            uses: julia-actions/cache@v1
          - name: Cache Quarto
            id: cache-quarto
            uses: actions/cache@v3
            env:
                cache-name: cache-quarto
            with:
                path: _freeze
                key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('*.qmd') }}
                restore-keys: |
                    ${{ runner.os }}-${{ env.cache-name }}-
          - name: Cache CondaPkg
            id: cache-condaPkg
            uses: actions/cache@v3
            env:
                cache-name: cache-condapkg
            with:
                path: /.CondaPkg
                key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('CondaPkg.toml') }}
                restore-keys: |
                    ${{ runner.os }}-${{ env.cache-name }}-
          - name: Install librsvg
            run: sudo apt-get install -y librsvg
          - name: "Render"
            run: "julia setup_render.jl"