name: Render 

on:
    push:
        branches: main
    pull_request:

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v4
          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
            with:
                # To install LaTeX to build PDF book 
                tinytex: true 
                # version: 1.3
          - name: Setup Julia
            uses: julia-actions/setup-julia@latest
            with:
                version: 1.9
          - name: Render Quarto Project
            uses: quarto-dev/quarto-actions/render@v2